INSERT INTO CATEGORY (NAME) VALUES ('Category 1');
INSERT INTO CATEGORY (NAME) VALUES ('Category 2');

INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Product1', 2000.00);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Product2', 800.00);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Product3', 80.00);

INSERT INTO PRODUCT_CATEGORY(PRODUCT_ID, CATEGORY_ID) VALUES (1,1);
INSERT INTO PRODUCT_CATEGORY(PRODUCT_ID, CATEGORY_ID) VALUES (2,1);
INSERT INTO PRODUCT_CATEGORY(PRODUCT_ID, CATEGORY_ID) VALUES (3,1);
INSERT INTO PRODUCT_CATEGORY(PRODUCT_ID, CATEGORY_ID) VALUES (2,2);

INSERT INTO STATE(NAME) VALUES ('SÃO PAULO');
INSERT INTO STATE(NAME) VALUES ('SANTA CATARINA');

INSERT INTO CITY(NAME, STATE_ID) VALUES ('BAURU', 1);
INSERT INTO CITY(NAME, STATE_ID) VALUES ('SÃO PAULO', 1);
INSERT INTO CITY(NAME, STATE_ID) VALUES ('FLORIANÓPOLIS', 2);

INSERT INTO CLIENT (CPF_CNPJ, EMAIL, NAME, TYPE) VALUES ('49627863181', 'client@email.com', 'John Doe', 1);
INSERT INTO CLIENT (CPF_CNPJ, EMAIL, NAME, TYPE) VALUES ('79746325000178', 'company@email.com', 'The Company', 2);

INSERT INTO PHONE_NUMBERS (CLIENT_ID, PHONE_NUMBERS) VALUES (1, '554822334455');
INSERT INTO PHONE_NUMBERS (CLIENT_ID, PHONE_NUMBERS) VALUES (1, '554899334455');
INSERT INTO PHONE_NUMBERS (CLIENT_ID, PHONE_NUMBERS) VALUES (2, '551152334455');

INSERT INTO ADDRESS(STREET, ZIP, NUMBER, NEIGHBORHOOD, COMPLEMENT, CITY_ID, CLIENT_ID) VALUES ('Almirante Alvim St',
'88015380', '555', 'Centro', '', 3, 1);
INSERT INTO ADDRESS(STREET, ZIP, NUMBER, NEIGHBORHOOD, COMPLEMENT, CITY_ID, CLIENT_ID) VALUES ('Matos Avenue',
'38777012', '105', 'Centro', '800', 2, 2);